project:
  type: website
  render:
    - index.qmd
    - paper.qmd
    - methods.qmd
    - cookbook.qmd
    - slides.qmd

website:
  title: "networkmerge"
  navbar:
    left:
      - href: paper.qmd
        text: "Networkmerge paper"
      - href: cookbook.qmd
        text: "parenx cookbook"
      - href: methods.qmd
        text: "Methods"
      - href: slides.qmd
        text: "Slides"
      - href: https://www.npt.scot
        text: "Network Planning Tool web application with simplified network"


format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto

