on:
    workflow_dispatch:
    # Run on Pull Requests
    pull_request:
      branches:
        - main
  
name: Quarto Publish

jobs:
  Reproducibility:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::ggplot2
            any::rcmdcheck
#       - name: Install deps
#         # Run the script in .devcontainer/install-additional-dependencies.sh
#         run: bash .devcontainer/install-additional-dependencies.sh

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2